version: '3.8'

services:
  app:
    build: .
    container_name: e-commerce-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0 
    container_name: mysql-db 
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ci4_db
      MYSQL_USER: ci4_user
      MYSQL_PASSWORD: user_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: