
# # AUTH

# POST http://localhost:8080/api/v1/auth/register
# content-type: application/json

# {
#    "name": "admin",
#    "email": "admin@example.com",
#    "password": "admin123",
#    "confirm_password": "admin123",
#    "role": "admin",
#    "address": "address Example",
#    "phone": "081234567890"
# }

# POST http://localhost:8080/api/v1/auth/login
# content-type: application/json

# {
#   "email": "admin@example.com",
#   "password": "admin123"
# }

# POST http://localhost:8080/api/v1/auth/logout
# content-type: application/json

# # USERS

# GET http://localhost:8080/api/v1/users
# content-type: application/json

# GET http://localhost:8080/api/v1/users/countuser
# content-type: application/json


# # GET http://localhost:8080/api/v1/users/1
# # content-type: application/json

# # DELETE http://localhost:8080/api/v1/users/2
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/users/4
# # content-type: application/json

# # {
# #   "name": "user4",
# #   "email": "user2@example.com",
# #   "password": "user123",
# #   "confirm_password": "user123",
# #   "address": "address Example",
# #   "phone": "081234567890"
# # }

# # CATEGORY

# POST http://localhost:8080/api/v1/category
# content-type: application/json

# {
#   "name": "yaya",
#   "description": "description categories example"
# }

# # DELETE http://localhost:8080/api/v1/category/1
# # content-type: application/json

# # GET http://localhost:8080/api/v1/category
# # content-type: application/json

# # GET http://localhost:8080/api/v1/category/3
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/category/3
# # content-type: application/json

# # {
# #   "name": "edit categories example",
# #   "description": "edit description categories example"
# # }

# Transactions

# POST http://localhost:8080/api/v1/transactions
# content-type: application/json; charset=UTF-8

# {
#   "total_price": 50000,
#   "status": "pending",
#   "status_delivery": "order",
#   "address": "thehok",
#   "cart_items_ids": [9, 11]
# }

# # DELETE http://localhost:8080/api/v1/transactions/1
# # content-type: application/json

# GET http://localhost:8080/api/v1/transactions
# content-type: application/json

# # GET http://localhost:8080/api/v1/transactions/3
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/transactions/3
# # content-type: application/json

# # {
# #   "user_id": 4,
# #   "total_price": 20000,
# #   "status": "paid"
# # }

# # Transactions

# POST http://localhost:8080/api/v1/transactions
# content-type: application/json

# {
#   "user_id": 1,
#   "total_price": 50000,
#   "status": "settlement",
#   "address": "thehok",
#   "status_delivery": "order"
# }

# # DELETE http://localhost:8080/api/v1/transactions/1
# # content-type: application/json

# GET http://localhost:8080/api/v1/transactions/paid
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/pending
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/cancel
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/user
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/getlatesttransactions
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/counttransactions
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/chartmonthgraph
# content-type: application/json

# GET http://localhost:8080/api/v1/transactions/countprofit
# content-type: application/json

# # GET http://localhost:8080/api/v1/transactions/3
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/transactions/3
# # content-type: application/json

# # {
# #   "user_id": 4,
# #   "total_price": 20000,
# #   "status": "paid"
# # }


# # Cart Items

# POST http://localhost:8080/api/v1/cartitems
# content-type: application/json

# {
#   "product_id": 2,
#   "quantity": 5
# }

# # DELETE http://localhost:8080/api/v1/cartitems/1
# # content-type: application/json

# GET http://localhost:8080/api/v1/cartitems/user
# content-type: application/json


# # GET http://localhost:8080/api/v1/cartitems/2
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/cartitems/3
# # content-type: application/json

# # {
# #   "product_id": 7,
# #   "user_id": 1,
# #   "quantity":5
# # }

# # Payment

# POST http://localhost:8080/api/v1/payments
# content-type: application/json

# {
#   "transactions_id": 16,
#   "payment_methode": "BCA",
#   "payment_status": "pending"
# }

# # DELETE http://localhost:8080/api/v1/payments/1
# # content-type: application/json

# # GET http://localhost:8080/api/v1/payments
# # content-type: application/json

# GET http://localhost:8080/api/v1/payments/getlatestpayment
# content-type: application/json

# # GET http://localhost:8080/api/v1/payments/2
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/payments/2
# # content-type: application/json

# # {
# #   "transactions_id": 1,
# #   "payment_methode": "MANDIRI",
# #   "payment_status": "success"
# # }


# # Product

# # post dan put lakukan di postman, karena di file ini tidak mundukung format file

# # DELETE http://localhost:8080/api/v1/products/11
# # content-type: application/json

# GET http://localhost:8080/api/v1/products
# content-type: application/json

# GET http://localhost:8080/api/v1/products/countproduct
# content-type: application/json

# # GET http://localhost:8080/api/v1/products/7
# # content-type: application/json



# # Stok In

# # POST http://localhost:8080/api/v1/stokin
# # content-type: application/json

# # {
# #   "product_id": 7,
# #   "quantity": 1
# # }

# # DELETE http://localhost:8080/api/v1/stokin/2
# # content-type: application/json

# # GET http://localhost:8080/api/v1/stokin
# # content-type: application/json

# # GET http://localhost:8080/api/v1/stokin/3
# # content-type: application/json


# # Transactions Items

# # POST http://localhost:8080/api/v1/transactionsitems
# # content-type: application/json

# # {
# #   "transactions_id": 1,
# #   "product_id": 7,
# #   "quantity": 6
# # }

# # DELETE http://localhost:8080/api/v1/transactionsitems/1
# # content-type: application/json

# # GET http://localhost:8080/api/v1/transactionsitems
# # content-type: application/json

# GET http://localhost:8080/api/v1/transactionsitems/inventory/5
# content-type: application/json

# # GET http://localhost:8080/api/v1/transactionsitems/3
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/transactionsitems/3
# # content-type: application/json

# # {
# #   "transactions_id": 1,
# #   "product_id": 7,
# #   "quantity": 10
# # }



# # Delivery

# POST http://localhost:8080/api/v1/delivery
# content-type: application/json

# {
#   "transactions_id": 5,
#   "status":"order"
# }

# # DELETE http://localhost:8080/api/v1/delivery/1
# # content-type: application/json

# GET http://localhost:8080/api/v1/delivery
# content-type: application/json

# GET http://localhost:8080/api/v1/delivery/send
# content-type: application/json


# GET http://localhost:8080/api/v1/delivery/order
# content-type: application/json

GET http://localhost:8080/api/v1/delivery/transactions/2
content-type: application/json


# GET http://localhost:8080/api/v1/delivery/pickup
# content-type: application/json


# GET http://localhost:8080/api/v1/delivery/complete
# content-type: application/json


# # GET http://localhost:8080/api/v1/delivery/trackingnumber
# # content-type: application/json

# # {
# #   "tracking_number": 24588285.00
# }

# # GET http://localhost:8080/api/v1/delivery/3
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/delivery/3
# # content-type: application/json

# # {
# #   "transactions_id": 1,
# #   "status":"send"
# # }


# # payment

# POST http://localhost:8080/api/v1/payments
# content-type: application/json


# {
#   "transactions_id": 1,
#   "payment_methode": "transfer"
# }

# # DELETE http://localhost:8080/api/v1/delivery/1
# # content-type: application/json

# # GET http://localhost:8080/api/v1/delivery
# # content-type: application/json


# # GET http://localhost:8080/api/v1/delivery/trackingnumber
# # content-type: application/json

# # {
# #   "tracking_number": 24588285.00
# }

# # GET http://localhost:8080/api/v1/delivery/3
# # content-type: application/json

# # PUT http://localhost:8080/api/v1/delivery/3
# # content-type: application/json

# # {
# #   "transactions_id": 1,
# #   "status":"send"
# # }


# # webhook

# POST  http://localhost:8080/api/v1/webhook
# content-type: application/json

# POST https://f092-36-50-201-47.ngrok-free.app/api/v1/webhook

# {
#   "order_id": "order_68175b268dac3",
#   "transaction_status": "expire"
# }
