# POST http://localhost:8081/users
# content-type: application/json

# {
#   "username": "admin",
#   "email": "admin@example.com",
#   "password": "admin123",
#   "confirm_password": "admin123",
#   "namalengkap": "Test User",
#   "handphone": "081234567890"
# }


POST http://localhost:8081/users/login
content-type: application/json

{
  "username": "admin",
  "password": "admin123"
}



